const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const mongoose = require('mongoose'); //requiring the mongoose library
const keys = require('../config/keys');  // ./ means look in the current directory, so you need 2 dots

const User = mongoose.model('users'); //we don't use require statements with mongoose for collections
        //sometimes you need to load in the collection multiple times and this confuses mongoose
        //here we are fetching out of mongoose
        //User is the model class

passport.serializeUser((user, done) => {
    done(null, user.id);  //this user id is the id generated by mongo
});

passport.deserializeUser((id, done)=> {
    User.findById(id)
    .then(user => {
        done(null, user);
    });
});

passport.use(
    new GoogleStrategy(
        {
        clientID: keys.googleClientID,
        clientSecret: keys.googleClientSecret,
        callbackURL: '/auth/google/callback',   // this is the route that user will be sent back to after they grant permission
        proxy: true
        }, 
        async (accessToken, refreshToken, profile, done) => {
            //console.log('access token', accessToken);
            //console.log('refresh token', refreshToken);
            //console.log('profile', profile);
            const existingUser = await User.findOne({ googleId: profile.id })
                
            if (existingUser) {
                //we already have a record with the given profile ID
                done(null, existingUser);
            }
            else {
                // we don't have a user record with this ID, make a new record
                const user = await new User({ googleId: profile.id })  //this creates the instance
                .save()
                done (null, user);
                //this is the same instance but coming back from dB, so fresher version
                //this creates one instance of a user, represents a user in our dB

                }
                
            
        }
    )
);